version: "3.9"
volumes:
  prometheus_data: {}

services:
  feature-service:
    build:
      context: ./ff/serving
      dockerfile: Dockerfile
    ports:
      - "2112:2112"
      - "8080:8080"
    expose:
      - 2112
      - 8080
  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    ports:
      - "8000:3000"
    expose:
        - 8000
  prometheus:
    build:
      context: ./metrics
    image: prom/prometheus:v2.1.0
    volumes:
      - ./prometheus:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090
    expose:
      - 9090
    restart: always