version: "3.9"
volumes:
  prometheus: {}
  prometheus_data: {}

services:
  feature-service:
    build:
      context: ./ff/serving
      dockerfile: Dockerfile
    ports:
      - "2112:2112"
      - "8080:8080"
    expose:
      - 2112
      - 8080
  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    ports:
      - "8000:3000"
    expose:
        - 8000
  prometheus:
    image: prom/prometheus:v2.21.0
    build:
      context: ./metrics
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: 
      - --web.enable-lifecycle  
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    expose:
      - 9090
    restart: always