apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-prometheus-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"

spec:
  selector:
    app: {{ .Release.Name }}-prometheus-server
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30001
