apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: feature-server
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    run: feature-server
status:
  loadBalancer: {}
---

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: feature-server
  name: feature-server
spec:
  replicas: 1
  selector:
    matchLabels:
      run: feature-server
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: feature-server
    spec:
      containers:
        - image: sami1309/grpc_server:latest
          name: feature-server
          ports:
            - containerPort: 8080
          resources: {}
status: {}
